### ISSUE TITLE
Try it now-Guide for Unikube

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#108]
Hackday December results can be posted here.

**Comment by marty-2015** [comment]
First steps: https://docs.google.com/document/d/18wzqiCEPCuUzk_BtbLPY_xVCQdrJ38TumFe3g8l6v0A/edit

**Comment by tobifroe** [comment]
The restructured guide can be found in [this PR](https://github.com/unikubehq/docs/pull/34).

**Comment by Truthans** [comment]
We either need to
a) consolidate our two current "getting started" guides:
- https://unikube.io/docs/guides/getting-started.html
- https://unikube.io/docs/getting-started/

or

b) change the naming of one guide to something like "try it now" or "give it a try"

Otherwise it's confusing.

**Comment by tobifroe** [comment]
@Truthans The section at https://unikube.io/docs/guides/getting-started.html doesn't have any content that's not in the new Getting Started section afaik. I think we could just remove https://unikube.io/docs/guides/getting-started.html altogether?

**Comment by tschale** [comment]
Would it make sense to have the getting started guide only under https://unikube.io/docs/guides/getting-started.html and have the menu entry (https://unikube.io/docs/getting-started/) link to that?

**Comment by Truthans** [comment]
> https://unikube.io/docs/guides/getting-started.html

@tschale yes, that would absolutely make sense. Can you take care of that?

**Comment by tschale** [comment]
@Truthans I might find some time in March to take care of that, if we can/want to wait until then...

**Comment by Truthans** [comment]
@tschale nah, that's way too long. @tobifroe do you see a chance to take care of that in the near future?:

> Would it make sense to have the getting started guide only under https://unikube.io/docs/guides/getting-started.html and have the menu entry (https://unikube.io/docs/getting-started/) link to that?

**Comment by tobifroe** [comment]
@Truthans This shouldn't take me too long. I might be able to get it done today, I can definitely do it this week.

**Comment by tobifroe** [comment]
@Truthans @tschale Done. Vuepress Sidebars only support two levels of nesting, so when you go to "Getting Started" from the guides sidebar, some context is lost. Should I look into somehow getting all the sidebar bullets or are you fine with this for now?

**Comment by Truthans** [comment]
> @Truthans @tschale Done. Vuepress Sidebars only support two levels of nesting, so when you go to "Getting Started" from the guides sidebar, some context is lost. Should I look into somehow getting all the sidebar bullets or are you fine with this for now?

I think it's fine for now. We'll do some real live testing and see what feedback we get.
