### ISSUE TITLE
Review Universal Illustration

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#111]
Final illustrations can be found here:
https://drive.google.com/drive/u/1/folders/1kFJd7Qo62gv3ecXbzIJbWMWwvgR-FKNZ

First drafts hackday: 
https://docs.google.com/presentation/d/1R6Ed5s4OHPxJ7pJbzxGBAGO9hfHYh_-CmNjbfAyFeFc/edit#slide=id.g1069fee0162_1_0

**Comment by marty-2015** [comment]
@Schille @SteinRobert we have 3 versions of the universal illustration now and we would like to know which one you like best.

Version 1:
![Bildschirmfoto 2021-12-20 um 11 32 10](https://user-images.githubusercontent.com/86047585/146753765-4e83da50-dae7-41c1-9296-2de99bc5f16e.png)

**Comment by marty-2015** [comment]
Version 2:
![Bildschirmfoto 2021-12-20 um 11 31 49](https://user-images.githubusercontent.com/86047585/146753842-342a439e-9df1-485f-96e4-a66f46ff3a3c.png)

**Comment by marty-2015** [comment]
Version 3: (similar to V1, but other "Release Process Arrow")
![Bildschirmfoto 2021-12-20 um 11 32 22](https://user-images.githubusercontent.com/86047585/146753950-bd504864-bf97-43ba-95bd-c126dcac4fec.png)

**Comment by marty-2015** [comment]
Version 2 briefed to Joel (30.12.); Change: 99% identical & App Code doesn't have to be displayed as boxes.

**Comment by marty-2015** [comment]
V1:
![Unikube RP - Infographic - V1 2](https://user-images.githubusercontent.com/86047585/149738684-6f8ccc9a-22c7-4051-89c1-bf7cf314b3a4.png)

**Comment by marty-2015** [comment]
V2: @Truthans please feedback
![Unikube RP - Infographic - V1 2 (Inverted)](https://user-images.githubusercontent.com/86047585/149738885-080c01df-1699-4ecf-8581-2a2c3c7e50fb.png)

**Comment by Schille** [comment]
Should we make "Helm / Manifests" to "Kustomize / Helm / Plain Manifests" ?

**Comment by marty-2015** [comment]
> Should we make "Helm / Manifests" to "Kustomize / Helm / Plain Manifests" ?

We wanted to make this illustration as simple as possible, so I would only change that if its really necessary for understanding. Otherwise I would think that when you see "OPs Team having something to do with manifests" - that the readers will understand what it means - don't you agree @Schille ?

**Comment by Truthans** [comment]
I'd leave the part of the manifests either as it is or just make it into "various manifests". Other than that I prefer the bright version. In the dark Version I feel the dark boxes don't work well with the background. Also, please make sure we get versions with transparent background too.

**Comment by marty-2015** [comment]
@Truthans @Schille here are the new versions. I think these are fine. My only feedback would be to make a dark outline on the white boxes in the transparent version.

V1 (transparent):
![Unikube RP - Infographic - V2 - Transparent](https://user-images.githubusercontent.com/86047585/151336011-6300f4ff-0c29-4561-875d-0faa5ee10d17.png)

**Comment by marty-2015** [comment]
V2 (dark):
![Unikube RP - Infographic - V2 (Inverted)](https://user-images.githubusercontent.com/86047585/151336101-4071168b-8708-4b21-903a-7e839ea1bdd1.png)

**Comment by marty-2015** [comment]
V3 (light):
![Unikube RP - Infographic - V2](https://user-images.githubusercontent.com/86047585/151336160-316d1783-e74e-4c15-8520-32850f838f42.png)

**Comment by SteinRobert** [comment]
V1 / V3 ❤️

**Comment by marty-2015** [comment]
Update: feedback given to joel, waiting for final version.

**Comment by Truthans** [comment]
Would be great if you could post a link here later to where in g drive these illustrations can be found.

**Comment by marty-2015** [comment]
> Would be great if you could post a link here later to where in g drive these illustrations can be found.

https://drive.google.com/drive/u/1/folders/1kFJd7Qo62gv3ecXbzIJbWMWwvgR-FKNZ
