### ISSUE TITLE
Add Conversion-Button (Frontend)

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#115]
Conversion-Button-Text: Try it now or Try for free

**Comment by tobifroe** [comment]
@Truthans @marty-2015 This is live, feel free to check it out

**Comment by marty-2015** [comment]
@tobifroe this also works, but there is one issue: When I click on it and I go back to the main page after, the text in the button disappears and reappears when I hover over it.

![Bildschirmfoto 2022-02-02 um 15 19 31](https://user-images.githubusercontent.com/86047585/152171918-9f03b542-f146-419c-8e56-4e7f078ce80b.png)

**Comment by tobifroe** [comment]
@marty-2015 @Truthans Just pushed a fix. Can you check again?

**Comment by marty-2015** [comment]
@tobifroe the text doesn't disappear anymore, thats fine. One more thing: The outline of the box (Schlagschatten) stays on the link after clicking on it and coming back to this page. Shouldn't the outline disappear altogether after clicking on the button?

When I come back to the page after clicking on it, the button appears like this:
![Bildschirmfoto 2022-02-03 um 10 46 03](https://user-images.githubusercontent.com/86047585/152319646-2350e3ac-388e-43e9-a9d1-673ec0c22267.png)

**Comment by marty-2015** [comment]
What we want it to appear is like this:
![Bildschirmfoto 2022-02-03 um 10 53 53](https://user-images.githubusercontent.com/86047585/152319837-d1417a78-98eb-4b14-a08f-e17329953b25.png)

**Comment by tobifroe** [comment]
@marty-2015 That's not a box shadow, that's the outline to tell you that the button is focussed (eg hitting enter while having it focussed would send you to the link destination again)

**Comment by marty-2015** [comment]
@tobifroe I see, but why would the button still be focussed after I visited the other page and returned back?

**Comment by tobifroe** [comment]
@marty-2015 Why wouldn't it be? Focus state is saved across tabs.

**Comment by marty-2015** [comment]
It just irritates me. @Truthans what do you think?

**Comment by Truthans** [comment]
That's fine, no change needed.
