### ISSUE TITLE
New: Two Buttons Plugin

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#116]
- Two buttons should be displayed next to each other
- This could be an add-on for the existing plugins: text, text&image, text&video 
- No background, dark blue border/font color

**Comment by tobifroe** [comment]
@Truthans @marty-2015 This is live, feel free to check it out

**Comment by marty-2015** [comment]
@tobifroe it works, but there is one issue: It seems to be expanding its size to the top, when there is not enough text on top of the button:
![Bildschirmfoto 2022-02-02 um 15 13 56](https://user-images.githubusercontent.com/86047585/152171057-73a180d0-ad5f-435b-8f5c-36995b618d81.png)

**Comment by Truthans** [comment]
And the green buttons have a disappearing font once they've been clicked.

![Bildschirmfoto 2022-02-02 um 15 21 45](https://user-images.githubusercontent.com/5262921/152172040-cc9ccc53-7433-43d3-9973-e5cdca4433d5.png)

**Comment by marty-2015** [comment]
@Truthans I just saw that on the conversion button as well. So I guess it applies to all the green buttons @tobifroe

**Comment by tobifroe** [comment]
@marty-2015 @Truthans Just pushed a fix. Can you check again?

**Comment by marty-2015** [comment]
@tobifroe the expanding size issue is now fixed, but we still have an issue with disappearing link-text. When I clicked on the secondary button and come back to the page and mouse over the button, the text disappears.

![Bildschirmfoto 2022-02-03 um 10 44 49](https://user-images.githubusercontent.com/86047585/152319293-4621e457-69c4-4840-93b9-32cf176a1f8d.png)

**Comment by tobifroe** [comment]
@marty-2015  My bad, I only checked this for the regular buttons. Fix is deploying right now
