### ISSUE TITLE
Invisible links in accordion with blue background

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#119]
The links (in green) are only visible, when the background color of the accordion plugin is white. They disappear when the background color is blue.

Example: FAQs
https://unikube.io/faqs/ (I have now set the background to white everywhere so that the links are readable.)

![Bildschirmfoto 2021-12-23 um 11 14 21](https://user-images.githubusercontent.com/86047585/147225604-5c91f0c8-6468-4b6f-936e-ef205928a045.png)

**Comment by marty-2015** [comment]
@tobifroe can you please have a look at this? I think its only a small issue.

**Comment by marty-2015** [comment]
Update (08.02.) this is next on the list

**Comment by tobifroe** [comment]
@marty-2015 Fixed, will be available in the staging environment in a minute.

**Comment by marty-2015** [comment]
@tobifroe I don't see it working in the preview mode. Does this have to be published to be visible?
<img width="1237" alt="Bildschirmfoto 2022-02-15 um 10 52 09" src="https://user-images.githubusercontent.com/86047585/154037301-54e176bb-193f-47ed-9e9e-c0ffc099c21d.png">

**Comment by tobifroe** [comment]
@marty-2015 My bad. Fixed now.
