### ISSUE TITLE
Django Hurricane Page for blueshoe.de

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#123]
I would also like to have a landing page on Blueshoe.de for django Hurricane and Gefyra, similar to the one for Unikube.

**Comment by marty-2015** [comment]
First preview: https://cms-dot-blueshoe-website-v4.ew.r.appspot.com/cms/pages/98/edit/preview/

**Comment by marty-2015** [comment]
@Truthans I have included a short introduction text. Can the page go live now?

**Comment by marty-2015** [comment]
@Truthans I have updated the page with the new features now.

**Comment by Truthans** [comment]
@marty-2015 I made some small changes and already published the page now. I also added the menu item. Please check this once the cache has run through. If everything is fine, this can be closed.

**Comment by marty-2015** [comment]
@Truthans since we write Django in capital letters everywhere on this page, I would also stick to this in the headlines. I didn't see any menu icon added, so I added the logo. Let's see how this works in the menu.

**Comment by marty-2015** [comment]
@SteinRobert @tschale I have changed a lot of the wording, please check again for a final review: 
https://cms-dot-blueshoe-website-v4.ew.r.appspot.com/cms/pages/98/edit/preview/

**Comment by tschale** [comment]
@marty-2015 Looks good! There is one sentence I would change a little, but maybe that's just personal preference.

Original:

> Außerdem bringt Django-Hurricane noch [weitere Features](https://www.blueshoe.de/blog/neue-features-fuer-django-hurricane/) wie Webhooks für Probe-Events, spezifische Management-Commands, einfache Konfigurationen sowie den Luxus mit, möglichst wenig Boilerplate Code schreiben zu müssen.


New:
> Außerdem bringt Django-Hurricane noch [weitere Features](https://www.blueshoe.de/blog/neue-features-fuer-django-hurricane/) wie Webhooks für Probe-Events, spezifische Management-Commands und einfache Konfigurationen mit, sowie den Luxus möglichst wenig Boilerplate Code schreiben zu müssen.

**Comment by marty-2015** [comment]
yap, thats personal preference I would say @tschale. I would like to leave it like that.

**Comment by marty-2015** [comment]
@Truthans can I publish the page now?

**Comment by Truthans** [comment]
Go ahead!
