### ISSUE TITLE
Backlink to Unikube from Docs

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#124]
Clicking on the Unikube logo when in "Docs" refers back to the Unikube Homepage - but when you are deeper into the navigation e.g. getting started/installation the backlink only refers to the docs landing page.

https://unikube.io/docs/ --> backlink to Unikube HP works

https://unikube.io/docs/guides/getting-started/ --> backlink to Unikube HP doesn't work but redirects to Wiki-Starting Page

**Comment by marty-2015** [comment]
@tobifroe another website topic for you

**Comment by tobifroe** [comment]
@marty-2015 Done.

**Comment by marty-2015** [comment]
thanks @tobifroe
