### ISSUE TITLE
Django Hurricane feature list

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#125]
We would like to have a list of advantages/features of Django Hurricane for the website. Maybe the list we have from Unikube [here](https://www.blueshoe.de/leistungen/unikube/) can be helpful. 

The list can be in german or english - whichever is easier.

**Die Vorteile von Unikube**

- Automatisierung und Standardisierung von Entwicklungsprozessen und Dokumentation.
- Einfache Reproduktion der Produktionsumgebung für die lokale Entwicklungsumgebung
- Entwickler müssen sich nicht mit Kubernetes befassen.
- Funktioniert für alle Umgebungen wie Staging oder Produktion.
- Konflikte beim Übergang von lokalem Code in den Cluster werden vermieden
- Kubernetes wird auch für kleinere Anwendungen nutzbar
- Durch mehr Automatisierung, weniger Risiko für menschliche Fehler.
- Automatisches Security-Profiling
- Automatisiertes Templating
- Einfaches Permission-Management

**Comment by marty-2015** [comment]
@vvvityaaa can you help me with this?

**Comment by vvvityaaa** [comment]
Here is the list of features:

- Better integration of Django and Kubernetes
- Tornado-powered Django application server
- Tornado-powered  Django AMPQ consumer
- Probe server out-of-the box with options for standard Kubernetes probes
- Webhooks to check up on the application status

**Comment by marty-2015** [comment]
thanks @vvvityaaa, can you please check whether this is the correct german translation?

- Bessere Integration von Django und Kubernetes
- Django-Anwendungsserver auf Tornado-Basis
- Tornado-getriebener Django-AMPQ-Anwender
- Sofort einsatzbereiter Probe-Server mit Optionen für Standard-Kubernetes-Untersuchungen
- Webhooks zur Überprüfung des Anwendungsstatus

**Comment by vvvityaaa** [comment]
- Bessere Integration von Django und Kubernetes
- Django-Anwendungsserver auf Tornado-Basis
- Django-AMQP-Anwender auf Tornado-Basis
- Sofort einsatzbereiter Probe-Server für Standard-Kubernetes-Sondierungen
- Webhooks zur Überprüfung des Anwendungsstatus

I think this way it should be better. I had a typo in AMQP, it is correct and not AMPQ, sorry about that.

**Comment by marty-2015** [comment]
great, thanks @vvvityaaa

**Comment by marty-2015** [comment]
@Schille @vvvityaaa I have created a new pull request for an update of the hurricane website - including this new feature list.

https://github.com/Blueshoe/django-hurricane/pull/54
