### ISSUE TITLE
Improving the Docs section

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#126]
Adding more text and links to the following sections:

- [x] getting started
- [x] next steps
- [x] guides
- [x] adding FAQ links all over docs

text doc: https://docs.google.com/document/d/1ADPFVgBRniPR0OoiYnXeFTQZe2Ianob4vNcBw504DGE/edit

**Comment by marty-2015** [comment]
@Truthans done, please review. I also changed the "Knowlede Base"-page a little bit by inserting a table of contents

**Comment by Truthans** [comment]
@marty-2015 reviewed and made a few changes. Please have a look and implement when happy.

**Comment by marty-2015** [comment]
Done.
