### ISSUE TITLE
Check link function

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#127]
Please check the link function for the help page: https://unikube.io/help/

Affected links are: 
- Get started
https://unikube.io/docs/guides/getting-started/

- Developing with Unikube
https://unikube.io/docs/guides/getting-started/developing-with-unikube.html

- Installing the Unikube CLI
https://unikube.io/docs/guides/getting-started/installation.html

**Comment by tobifroe** [comment]
@marty-2015 Fixed, the links on the help page work as expected now.

**Comment by marty-2015** [comment]
Yes, it works now. Thanks @tobifroe
