### ISSUE TITLE
Change padding before/after image block

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#129]
I want to insert this illustration (see screenshot) on the blueshoe/unikube website. The padding is so huge, that it looks like a mistake. Can we make the spacing smaller please?

Also visible here: https://www.blueshoe.de/leistungen/django-hurricane/

website: https://www.blueshoe.de/leistungen/unikube/

![Bildschirmfoto 2022-02-02 um 10 32 23](https://user-images.githubusercontent.com/86047585/152128584-81913747-d8a6-476c-901a-004d15dea36b.png)

**Comment by marty-2015** [comment]
Task update: First thing on the list (08.02.)

**Comment by tobifroe** [comment]
@marty-2015 Fixed, will be available in the staging environment in a minute.

**Comment by marty-2015** [comment]
@tobifroe I don't really see a big space difference here at the top: https://cms-dot-blueshoe-website-v4.ew.r.appspot.com/cms/pages/70/edit/preview/

**Comment by tobifroe** [comment]
@marty-2015 I reduced the padding further (now 80px less than what it was before).
