### ISSUE TITLE
Google Tag manager in docs pages

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#132]
@tobifroe we want to track where users may leave the journey in the getting started guide. Therefore I need our tag manager snippet to also be included in all pages under https://unikube.io/docs/

Can you integrate the following snippet just at the top of the <head> tag:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-MKVRSF6');</script>

And the following snippet directly after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MKVRSF6"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by Truthans** [comment]
@tobifroe man, it really sucks to integrate the code snippets here. I put them in a doc:

https://docs.google.com/document/d/1OuesTrHY2v7fQuLMPaipFT8DGxQlxB1k7XVTPNesja0/edit?usp=sharing

**Comment by tobifroe** [comment]
Wrapping snippets in triple backticks ``` should do the trick:
```
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src= 'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f); })(window,document,'script','dataLayer','GTM-MKVRSF6');</script>
```
And the following snippet directly after the opening tag:
```
<iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MKVRSF6" height="0" width="0" style="display:none;visibility:hidden"></iframe>
```

**Comment by tobifroe** [comment]
@Truthans Just added the scripts. Chances are you'll see a cached version now (at least I do), but you should be able to check it out in an hour max.
