### ISSUE TITLE
Integrate new feature list

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#140]
New Feature List:
https://docs.google.com/document/d/1d9lUIqJDOX7CqZSn1e8F_X0V9Frlm9hrdHLeUaU1x2U/edit

**Comment by marty-2015** [comment]
@Truthans  @Schille  I just made a new feature page, its called "Features NEU" - the old page still exists. The new one is saved as a draft here: https://cms-dot-blueshoe-website-v4.ew.r.appspot.com/cms/pages/100/edit/ Please check it out.

Feedback: Michael Schilonka, Fri 10:55
- ohne grafiken wirkt es ziemlich dense, aber ok.
- gefällt mir besser als unsere aktuelle feature seite 🙂

Feedback Melanie
- es ist sehr viel Text - ja, finde ich auch - aber wenn ich deine Vorlage nehme und überall das Plugin Text+Bild rein mache, wird die Seite extrem lang und man verliert dann schnell den Überblick, was die Key-Features eigentlich sind.
- Für das Plugin Bild+Text bräuchten wir außerdem größere Grafiken als die kleinen Icons, die wir aktuell haben.

**Comment by Schille** [comment]
Thanks for bringing this up. What is my task here?

**Comment by Truthans** [comment]
@Schille @marty-2015 I published the page now, since it's clearly better than the old one but I think the old one is still in cache. We should still replace the icons for the steps 1 - 3.
