### ISSUE TITLE
Create Unikube YouTube Channel

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#17]
- [x] Create channel
- [x] create graphics
- [ ] post first video(s)
- [ ] Invite subscribers

**Comment by marty-2015** [comment]
Header proposal @Truthans 
https://drive.google.com/drive/folders/1WZmTsieTxGWgg1IbdR_A8wUAxgXZDy1h

**Comment by marty-2015** [comment]
YouTube Channel
https://www.youtube.com/channel/UCPpSDnhRyuMNx9wRbqMSLLg/about
