### ISSUE TITLE
Implement new E-Mail signatures

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#18]
- [x] Create new siganture
- [x] Roll out company wide once new website is live

**Comment by marty-2015** [comment]
Hier ist ein Link, um eine Signatur zu erstellen, die meiner entspricht: https://www.hubspot.de/email-signature-generator?customCtaColor=%2300dd99&customCtaTextColor=%23ffffff&fontFamily=Arial&fontSize=medium&linkColor=%23000630&logoImage=https%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1ufcI33t-8CcPwMbuLccg57s8Ref1sg19&template=templateOne&textColor=%23000000&themeColor=%23000630&viralToggle=false

**Comment by Truthans** [comment]
@marty-2015 du musst den Link in der Signatur noch anpassen, der geht immer noch auf die www. subdomain. Signatur ist approved. Bitte jetzt Termine mit jedem machen, Signatur vorbereiten und implementieren.

**Comment by marty-2015** [comment]
Hier ist ein Link, um eine Signatur zu erstellen, die meiner entspricht: https://www.hubspot.de/email-signature-generator?customCtaColor=%2300dd99&customCtaTextColor=%23ffffff&fontFamily=Arial&fontSize=medium&linkColor=%23000630&logoImage=https%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D13L1EqKWcb8aF8g8kxkSZd9wHdC1BhRH6&template=templateOne&textColor=%23000000&themeColor=%23000630&viralToggle=false
