### ISSUE TITLE
Necessary changes in footer

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#22]
Change postcode to "80337"
Change "ADRESSE" to "ADDRESS"
Change "KONTAKT" to "CONTACT"

**Comment by Truthans** [comment]
Hi @tobifroe, is it ok if I assign this ticket to you?

**Comment by tobifroe** [comment]
Sure @Truthans. Maybe we should add a label for dev related website issues or create a new project to separate dev issues from actual content todos, what do you think?

**Comment by Truthans** [comment]
@tobifroe makes sense. I'll take of it for any future dev tasks.

**Comment by tobifroe** [comment]
@Truthans Done, I guess you can mark this as resolved.

**Comment by Truthans** [comment]
Moved this into a new project just for the technical part of the website. And closing the issue.
