### ISSUE TITLE
Feature List

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#25]
I'd like to move the features away from the home page and give them their own space.

This would be the page:
https://cms.unikube.io/features/

- [x] Decide on feature structure
- [x] List features and describe them
- [ ] Enrich with media (pics, video)
- [x] Proof reading
- [x] Publish

**Comment by Truthans** [comment]
I will provide a first draft of the features

**Comment by Truthans** [comment]
I have created a first draft. I think it's not visible live yet, but just in preview mode:
https://cms-dot-blueshoe-website-v4.ew.r.appspot.com/cms/pages/81/edit/preview/

Would be great to enhance this.

Can you have a look @SteinRobert @Schille ?

**Comment by marty-2015** [comment]
@Truthans I have added pictures in the preview mode, please check.
