### ISSUE TITLE
Mail Outreach

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#27]
- [x] identify targets
- [x] Prepare mail text
- [x] Create demo link in hubspot
- [x] Shoot

**Comment by Schille** [comment]
How may I support this process at this point?

**Comment by Truthans** [comment]
@Schille 
Here is the list of companies I'd like to re-connect to now. If put in a column who should do it. I think your contacts should be very personal.
https://docs.google.com/spreadsheets/d/1VneioNUi3VNdrW-WuMhD8DdCsLn5Yg6B3ursTV3aL1A/edit?usp=sharing

I'll contact my guys with the template I recently showed you.

I created a new demo link for you, which should be synced with your calendar. At the moment it doesn't have free appointments so we need to check later, whether this works properly:
https://email.blueshoe.de/meetings/michaelschilonka/unikube-demo

Our goal should be to send out mails again on 12.08.2021

**Comment by Truthans** [comment]
@Schille is your calendar still connected to HubSpot? The meeting link in general seems to work, but it doesn't seem to consider any of your booked times. I don't know why. I also compared it with our group meeting link which we used in the past and which used to work well, it definitely takes my appointments into consideration but not yours. 

Hence, it looks definitely like your calendar is disconnected. Can you please check this urgently as I can't send out mails otherwise.

**Comment by Schille** [comment]
@Truthans don't know why I had to connect it again. Anyway it seems to be working now.

**Comment by Truthans** [comment]
@Schille now that I am back from holiday I created a new demo booking link, that involves both of us:
https://meetings.hubspot.com/hannes/unikube-demo
