### ISSUE TITLE
Image Block Changes

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#28]
@tobifroe I tried the ImageBlock today: https://youtrack.blueshoe.de/issue/BSW-255

- The plugin forces me to input text. Should be optional
- The plugin forces me to decide for the position "left" or "right". I should have the option "center" too. Image should be full size with this plugin
- When I add the plugin to the website, the preview breaks and returns a server error

Can you have a look at this?

**Comment by tobifroe** [comment]
@Truthans Fixed, text is now optional, I added "center" as an alignment option + the preview works as expected.

**Comment by Truthans** [comment]
@tobifroe unfortunately when using a .svg file the preview still returns a server error.

**Comment by tobifroe** [comment]
@Truthans My bad. .svg files are fixed now.

**Comment by Truthans** [comment]
Yep, that works. Thank you!
