### ISSUE TITLE
LinkedIn Post: Change Management Effectiveness

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#3]
https://docs.google.com/document/d/1zvd7mW0LMxunSqNBZreABfIIJnxBtoI7Gf5E476XGkc/edit?usp=sharing

- [x] Expand copy text
- [x] Create post formatted for LinkedIn

**Comment by marty-2015** [comment]
@Schille please post in DevOps Group: https://www.linkedin.com/groups/2825397/

**Comment by Truthans** [comment]
Posted. But is now in the hands of the group admins.

**Comment by marty-2015** [comment]
Thanks

**Comment by Truthans** [comment]
- [ ] Check again if published in DevOps group and if not, submit again or post on private profile.

**Comment by Truthans** [comment]
Seems this was never published. I'll post it on my private profile next week and potentially the Unikube page.

**Comment by Truthans** [comment]
Posted on my private account.
