### ISSUE TITLE
Corrections of blog overview page

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#31]
Hi @tobifroe,

the blog overview page shows a few behaviors that need to be corrected. See video attached.

https://user-images.githubusercontent.com/5262921/124748083-f65b6900-df22-11eb-9476-8a058004f7b0.mp4

**Comment by tobifroe** [comment]
@Truthans This is fixed. FYI: The grey background was caused by the button being in focus. I changed the focus style to match the hover style in this section.

**Comment by Truthans** [comment]
Works, thanks a bunch!
