### ISSUE TITLE
Modal view for HeaderVideoSection

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#32]
Hi @tobifroe, the video in the header section is relatively small at the moment. Yesterday we though about a quick solution. Can you give the plugin the option, that the video will open in a bigger modal when the user presses play?

**Comment by tobifroe** [comment]
@Truthans As in, adding a checkbox "open in modal" to the plugin admin?

**Comment by Truthans** [comment]
Correct. Would that work?

Von meinem iPhone gesendet

**Comment by Truthans** [comment]
However, if it's easier right now, we could just make it as a default for the time being.

**Comment by tobifroe** [comment]
@Truthans Videos now open in a modal by default, I'll look into adding modals as an option next week.
