### ISSUE TITLE
Devops Evolution Model Infografik

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#37]
Convert attached infographic into a unikube style infographic with Joel Knifeld via upwork.

Two of the icons are currently the same. General style is pretty good, so it may just need a few more tweaks.
Also, proofreading would be nice.

![cloud_native_evolution_model (1)](https://user-images.githubusercontent.com/5262921/124899752-b65abb80-dfe0-11eb-8b32-80875e29e0ed.png)

**Comment by Schille** [comment]
Today, I got a new version from Joel

**Comment by marty-2015** [comment]
Editors feedback:
[Cloud-Native Development Evolution Model - Sheet1_Annika Edit.pdf](https://github.com/unikubehq/marketing/files/6840570/Cloud-Native.Development.Evolution.Model.-.Sheet1_Annika.Edit.pdf)

**Comment by Schille** [comment]
Sure. I have two version. This is the color-inverted one.
![Unikube C-NDEM - Infographic (Inverted)HalfSize](https://user-images.githubusercontent.com/676722/126162481-a2284c22-c54d-43e8-82fd-6afb86972967.png)

**Comment by Schille** [comment]
I'd put a "Stage" above the number so it's more clear. The Editor's feedback seems to be resolved already.

**Comment by marty-2015** [comment]
Feedback:
- I don't like the radar beams, because they distract from the main content, also the writing gets way too small when we have that much space on the sides. 
- Kubernetes is the only green icon (draws a lot of attention). Either all blue or all mixed? 
- editors feedback still has to be worked in
- bullet points (actual points) are missing (sections 4+5)
- Section 3 (examples): is it "event streams interfaces" or "event streams / interfaces" ?
- Unikube is not included as an Example in any of the 5 stages. Why?

**Comment by Schille** [comment]
That's the version I would go with. I cannot see starkly required adjustments anymore.
![Unikube C-NDEM - Infographic (Inverted) (V2)](https://user-images.githubusercontent.com/676722/127029832-b3747be8-aa04-4f55-83ab-6df9efcc6e6c.png)

**Comment by Schille** [comment]
What would you @unikubehq/tech-marketing like to do with it next? Have a blog article about it?

**Comment by marty-2015** [comment]
Ja Blog-Artikel macht Sinn. Für Social Media ist die Grafik nicht wirklich geeignet. Habs grad mal probeweise auf Linkedin gestellt. Siehe Screenshot.
![Bildschirmfoto 2021-07-27 um 09 58 30](https://user-images.githubusercontent.com/86047585/127122683-1cf205d8-0f93-463d-8211-343c11800bfb.png)

**Comment by Schille** [comment]
Yes, you're right. It's just not working for social media. But now I think the briefing was already not suitable for social media in the first place.

**Comment by marty-2015** [comment]
Yes, its too much text. But I talked to @Truthans yesterday and he thinks we can post it anyway, if we link to the blog with a better display of the visual.

**Comment by Truthans** [comment]
@marty-2015 do you think you can work out a blogpost for this or do you prefer me to do it?

**Comment by Truthans** [comment]
@Schille I have written a small article around the model:
https://docs.google.com/document/d/1TF87HPzgbMLR8gHD6ujbdNpPnUeikrCnjT86D7cmlS0/edit?usp=sharing

Also, there is a type in Stage 4 in the illustration: "Continues Integration" --> "Continuous Integration"
Als, is there a comma missing between ArgoCD and Service Mesh?

**Comment by tschale** [comment]
@Truthans I've reviewed the article. Overall I think it looks good, although there might be a little bit more content at stage 4 and 5, just as it is at stages 1-3.

**Comment by Schille** [comment]
I requested the required changes for the illustration.

**Comment by marty-2015** [comment]
Please review @Schille https://unikube.io/blog/cloud-native-development-evolution-model
