### ISSUE TITLE
Title Tag still displays Blueshoe automatically

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#39]
See screenshot for blog
<img width="827" alt="Bildschirmfoto 2021-07-08 um 16 09 04" src="https://user-images.githubusercontent.com/86047585/124936486-e3ba6000-e006-11eb-8578-d20bd7901a5e.png">

**Comment by Schille** [comment]
This seems to be hard-coded in `frontend/.nuxt/index.js` Line 86. I forward that issue to @tobifroe

**Comment by tobifroe** [comment]
@marty-2015 Fixed, title tags on unikube.io now end with "| UNIKUBE".
