### ISSUE TITLE
LinkedIn Post: Lack of standardization creates problems

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#4]
https://docs.google.com/document/d/171Cs997toA4inxG7dwFnzuTeQrw78rocKtoohWfY60c/edit

- [x] Expand copy text
- [x] Format for LinkedIn Post

**Comment by marty-2015** [comment]
@Truthans please check edited text

**Comment by marty-2015** [comment]
Some ideas for visuals @Truthans 
https://www.canva.com/design/DAEk0apjEzc/EICBIPsigpYIHZXGacwbCQ/view?utm_content=DAEk0apjEzc&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by marty-2015** [comment]
Visuals upated

**Comment by marty-2015** [comment]
Finalized

**Comment by Schille** [comment]
done. I added a link to unikube.io as it appeared to be missing.

**Comment by marty-2015** [comment]
General Question: Do we want to post the link in every post? I left it out on purpose, because we wanted to start a conversation on the topic, not on unikube at first. I think posting the link in the comments of the discussion would be a better option. What do you think @Truthans

**Comment by marty-2015** [comment]
@Schille We want to try out different channels to see which one works best. So we want to post this again in two weeks, on your personal linkedin account, without the picture, just the text. I will set a new milestone.

**Comment by Schille** [comment]
done today
