### ISSUE TITLE
Button not displaying correctly

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#40]
@tobifroe in the mobile view of the blog overview section, the filter articles button doesn't display correctly and is still in German language. Would be good to change it to "filter articles"

![IMG_3894](https://user-images.githubusercontent.com/5262921/125061610-cc827d80-e0ad-11eb-88eb-d10de589e1f6.PNG)

**Comment by tobifroe** [comment]
@Truthans The mobile filter button works as intended now.
