### ISSUE TITLE
Website icons

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#43]
Following icons would be needed from our pakistani agency on Upwork:

- [ ] Cloud (hosted)
- [ ] On Premise
- [ ] Developer
- [ ] Operations
- [ ] Manager
- [ ] Platform
- [ ] CLI
- [ ] Automation

**Comment by Truthans** [comment]
@SteinRobert I remember, that you also wanted a few more icons?

**Comment by SteinRobert** [comment]
Yes! Good thank you remembered :) 

1. We need an icon for "synchronization".
It will be used on the project list (https://app.zeplin.io/project/5f84546964e43c2749571f59/screen/5f845c6ce1cb3f27e42e4ee9) next to the edit and delete icon.
2. A terminal icon. Same as the previous one, will be used like the delete and edit icons.
3. We're using snackbars (https://app.zeplin.io/project/5f84546964e43c2749571f59/screen/5f845cc4fc28f12a915ea2bc). Currently we only have a success icon for the snackbar. Would be great if we had a warning and an error icon, too.

**Comment by SteinRobert** [comment]
Is this already progressing? I have another icon to add:
It would be great if we had a ship's wheel as an icon.

**Comment by Truthans** [comment]
@SteinRobert it's in progress now. I just briefed it but need to wait for the freelancer to accept the job.

**Comment by Truthans** [comment]
@SteinRobert here are your icons, do you have feedback / change requests?:
https://projects.invisionapp.com/share/CUYLNLP58MK#/screens/456467289_Webapp_-_Icons

Here are also the new website icons:
https://projects.invisionapp.com/share/CUYLNLP58MK#/screens/456467288_Website_-_Icons

I like all of these.

**Comment by Truthans** [comment]
@marty-2015 I have added you to a conversation on Upwork regarding the icons. The icons that the agency designed are good but we have not yet received the pngs and svgs. Once we get these, can please forward the ones Robert requested to him and save the ones that we wanted for website as well as trying if they work.

If there are changes necessary, please take care of it.

**Comment by marty-2015** [comment]
@SteinRobert I have put the icons in this folder https://drive.google.com/drive/folders/1GljQk5SgyBN-mmtpVxC0VJf-UyX1lQix
As far as I can see, we have all the images, that you requested. Right? If there is something else missing, please let me know.

**Comment by marty-2015** [comment]
One more question @SteinRobert: I just saw that some of the icons only work on colored background (like devops, developers, managers, error) - that was intended, right?

**Comment by SteinRobert** [comment]
Unfortunately idk. The icons we requested for the application are fine. The ones for the website I haven't briefed, therefore I don't know how these are meant to be used.

**Comment by marty-2015** [comment]
Ok, I think we haven't briefed other versions for the website, so this should be fine for now.
