### ISSUE TITLE
LinkedIn Post: An end to context switching

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#5]
https://docs.google.com/document/d/1bZ7EUoeYQROPKpHJiqUX87uJTIaQNnCCwPSmJdZlBGE/edit?usp=sharing
- [x] Expand copy text
- [x] Prepare for posting on LinkedIn

**Comment by marty-2015** [comment]
@Truthans please check edited text

**Comment by marty-2015** [comment]
Some ideas for visuals @Truthans 
https://www.canva.com/design/DAEk0apjEzc/EICBIPsigpYIHZXGacwbCQ/view?utm_content=DAEk0apjEzc&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink

**Comment by marty-2015** [comment]
To Do: implement feedback for visuals

**Comment by marty-2015** [comment]
Visuals updated

**Comment by marty-2015** [comment]
Finalized

**Comment by marty-2015** [comment]
@Schille please post in Linkedin DevOps group:
- Text (V2) and Image: https://docs.google.com/document/d/1bZ7EUoeYQROPKpHJiqUX87uJTIaQNnCCwPSmJdZlBGE/edit
- DevOps Group: https://www.linkedin.com/groups/2825397/

**Comment by Schille** [comment]
done today.
