### ISSUE TITLE
Static Page Generator for documentation and knowledgebase

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#50]
For the unikube documentation as well as our cloud native knowledgebase, we would like to implement a static page generator (like gatsby) in order to integrate contenbt via markdown.

Additional requirements:
- Should run in a folder of the main domain, not on a subdomain

Attached are a few designs, that we had made a while ago. These are not set in stone.

**Comment by Truthans** [comment]
Here are the knowledge base designs:
https://drive.google.com/drive/u/0/folders/1YNY8_9f2M-Z-al9kQpVEiswMcCAtlzZv

**Comment by tobifroe** [comment]
@Truthans FYI: I created a [new repo](https://github.com/unikubehq/docs) for this.

**Comment by SteinRobert** [comment]
The site is live and WIP: https://unikube.io/docs/

**Comment by Truthans** [comment]
Holy cow! Nice job guys!

**Comment by Truthans** [comment]
@tobifroe would be great if you could give @marty-2015 and me a little introduction to the publishing process via Github.
