### ISSUE TITLE
Expand Video-Plugin to YouTube Integration

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#52]
Since we can only upload videos up to 10/32MB we want to expand the Video-Plugin to be able to integrate links form YouTube.

**Comment by Schille** [comment]
I think this just got deployed. Please close this issue if you can confirm it working.

**Comment by marty-2015** [comment]
@tobifroe can you please check the video play function again? I inserted a new content block (under features) and push the play button, the video opens in a bigger window, but doesn't start playing. This also happend in the preview, but now its the same in live mode.

**Comment by Schille** [comment]
Youtube seems to be still not really working. I temporarily switched the video to one we have in the GCP storage bucket.

**Comment by marty-2015** [comment]
The video works now. Thanks.
