### ISSUE TITLE
Images Issue Tiles

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#54]
I have changed the images (svgs) in the tile section for features two times this week and it still shows the "old" images I tried last thursday. For the CLI image it doesn't display anything at all (See screenshot). Is there something wrong with cache clearing?

**Comment by marty-2015** [comment]
<img width="1218" alt="Bildschirmfoto 2021-08-19 um 08 54 56" src="https://user-images.githubusercontent.com/86047585/130022711-0d549d40-471f-457b-b465-968a6cd415c4.png">

**Comment by tobifroe** [comment]
The CLI icon is not available in our [storage bucket](https://storage.googleapis.com/blueshoe-website-v4.appspot.com/documents/CLI.svg). I tried reuploading but no luck. @Schille Any idea why this would happen?

@marty-2015 The platform/automation icons are the correct ones that were set in the admin interface, did you publish your changes correctly?

**Comment by Schille** [comment]
I uploaded the CLI.svg using the GCP console. It's working now. Please open up another issue if we have a general problem with document uploads.
