### ISSUE TITLE
Blog: Migration to Cloud Native

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#55]
https://docs.google.com/document/d/1yjFBiBoWMw3udDMAAYNuG15ghYekuO8ITueL779Gj0c/edit#

- [x]  Translation
- [x]  Enter in CMS
- [x]  Complete Meta Data and URL structure
- [x]  Add filters
- [x]  Add all hyperlinks
- [x]  Remove references to blueshoe
- [x]  Publish

**Comment by marty-2015** [comment]
translation requested

**Comment by marty-2015** [comment]
@Schille @tschale please take a quick look at the published blog post (new pics). If this looks good, I can post it on social media this week.

**Comment by marty-2015** [comment]
@Schille please share our post on LinkedIn to the Kubernetes Group
- Link to post: https://www.linkedin.com/feed/update/urn:li:activity:6840922750723387392
- Kubernetes Group: https://www.linkedin.com/groups/6821178/
- Teaser text: Anyone dealing with the challenge of migrating existing projects into the Cloud Native workflow? These 3 examples might help you!

**Comment by Schille** [comment]
Love it.
