### ISSUE TITLE
General problem with document/svg upload

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#56]
I have changed the images (svgs) in the tile section for features and "what unikube is for" today and published it. It displays 3 of the 6 icons in the preview mode correctly, the other ones are still old svgs.

**Comment by Truthans** [comment]
@Schille would be great if you could look at this as soon as possible, as with the mail outreach to investors and potential customers, we will have a few more people on the website.

**Comment by Schille** [comment]
I think I know what happened here. There is no general problem with document/svg upload - I tried it myself. 

However, once you upload a `document` (i.e. SVG) wagtail creates a reference to that very document in the storage location. The wagtail reference is then taken to apply it on several blocks/location in the CMS.
You updated these SVGs with exactly the same document name (e.g. `CLI.svg`) which caused wagtail to create a second wagtail reference pointing to the overwritten document (i.e. `CLI.svg`). I suppose wagtail delete the first version in the process (by overwriting it) and was not able to add it in the same transaction creating a second reference. 
To fix this issue in the meantime, I uploaded all missing SVGs again with its title as the wagtail reference title. The document is now present in the storage, hence the references from the CMS blocks are now working, too.
I'd say in the meantime be cautious with uploading same document names multiple times while creating mutliple references (that is: new upload, same document name). Please make use of the document edit view and exchange the file from the originally created wagtail document reference.
