### ISSUE TITLE
Setting up Google Analytics

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#59]

**Comment by Truthans** [comment]
@tobifroe could you please add the following script to the unikube base template?

`
<script async src="https://www.googletagmanager.com/gtag/js?id=G-H6N3GK3B5K"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-H6N3GK3B5K');
</script>`

**Comment by tobifroe** [comment]
@Truthans Something like [this](https://google-analytics.nuxtjs.org/) would be the clean solution. Would that work for us?

**Comment by Truthans** [comment]
@tobifroe yes, as it looks I'd say this would work.
