### ISSUE TITLE
False Meta Description

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#64]
When the link for the blogpost was posted in Google Chat, it still displayed "Blueshoe"  - though it doesn't say so in the meta descriptions I added. There must be some overall meta tag still running on blueshoe.

**Comment by marty-2015** [comment]
<img width="481" alt="Bildschirmfoto 2021-09-01 um 16 23 42" src="https://user-images.githubusercontent.com/86047585/131690337-8d398759-bd22-4956-84e6-9a31caac7067.png">

**Comment by marty-2015** [comment]
My To Do: https://validator.schema.org/#url=https%3A%2F%2Funikube.io%2Fblog%2Fmigration-to-cloud-native%2F

**Comment by marty-2015** [comment]
@tobifroe here is a new list for you: https://docs.google.com/spreadsheets/d/1nLYDM5PW2mjcsL6iLO9OtqedcUYF8lyaBMwlcmKKSuY/edit#gid=1154914244

**Comment by tobifroe** [comment]
Done. To double check, have a look at the [validator](https://validator.schema.org/#url=https%3A%2F%2Funikube.io%2Fblog%2Fmigration-to-cloud-native%2F).

**Comment by marty-2015** [comment]
@tobifroe can you please change one more thing? 
WebSite
alternateName | Blueshoe Digital Products --> Unikube

**Comment by tobifroe** [comment]
@marty-2015 Done. :)
