### ISSUE TITLE
Cookie Settings

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#66]
In order to give users the option to change their cookie settings, HubSpot needs us to implement the following code snippet on the page on which the settings should appear:

```
<!-- Anfang des HubSpot-Code-Snippets -->
<button type="button" id="hs_show_banner_button"
  style="background-color: #2470a9; border: 1px solid #2470a9;
         border-radius: 3px; padding: 10px 16px; text-decoration: none; color: #fff;
         font-family: inherit; font-size: inherit; font-weight: normal; line-height: inherit;
         text-align: left; text-shadow: none;"
  onClick="(function(){
    var _hsp = window._hsp = window._hsp || [];
    _hsp.push(['showBanner']);
  })()"
>
  Cookie-Einstellungen
</button>

<!-- Ende des HubSpot-Code-Snippets -->
```

Here is more info:
https://knowledge.hubspot.com/de/reports/customize-your-cookie-tracking-settings-and-privacy-policy-alert#schaltfl%C3%A4che-%E2%80%9Ecookie-einstellungen%E2%80%9C-zum-cookie-richtlinienbanner-hinzuf%C3%BCgen

We may have to create a page for that or use the data privacy page. Let's discuss this next week.

**Comment by tobifroe** [comment]
@Truthans I added a block called "HubspotCookie", it can be used in any StandardPage and returns the snippet centered in a div. I added it to https://unikube.io/data-privacy/.

**Comment by marty-2015** [comment]
@tobifroe I have inserted the new cookie button on both pages (UK and BS) now.
Since there is a lot of white space in the middle of the text now, can you make the padding around the button a little bit smaller?
![Bildschirmfoto 2021-10-11 um 15 01 16](https://user-images.githubusercontent.com/86047585/136794588-a948080d-6de7-4a74-a774-1540a3b36b8a.png)

**Comment by tobifroe** [comment]
@marty-2015 I can change the button spacing, sure. 
I don't know wether we can reuse the cookie snippet on blueshoe.de, there might me some settings to change before we do? @Truthans might be able to tell us.
