### ISSUE TITLE
Text for Reddit Post

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#71]

**Comment by Truthans** [comment]
@Schille I created the following text on the base of your last post in the linkedIn django group. Could you post this in the following groups:

```
Hi all,

we're currently building 🔨 a novel open-source platform for Kubernetes native application development: https://unikube.io - and now we are really looking for some feedback to advance the development of the project. 👀

In line with the spirit of open source communities we’d really appreciate if you could spare some time to take a look. Just leave a comment or drop me a message and I’ll reach out and give you a tour / little demo.

Thanks a bunch in advance!🖖
```
-> You may have to adapt this a little for reddit, since I don't know if there even is messaging or just commenting!

https://www.linkedin.com/groups/6821178/
https://www.reddit.com/r/kubernetes/

**Comment by Schille** [comment]
https://www.reddit.com/r/kubernetes/comments/ppvwbv/feedback_for_a_new_open_source_k8snative/
