### ISSUE TITLE
Research Start-Up Events und Pitch Events

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#77]
https://docs.google.com/spreadsheets/d/1BtJrmX8b3SMdCD8ThohzLEWp5OKLzc60Chzfx14yqzM/edit#gid=0

Ideally we have some sort of calendar with all relevant pitch and startup events for Unikube

**Comment by marty-2015** [comment]
https://docs.google.com/spreadsheets/d/1BtJrmX8b3SMdCD8ThohzLEWp5OKLzc60Chzfx14yqzM/edit#gid=0

**Comment by marty-2015** [comment]
@Truthans let's have a meeting on that topic and discuss which events are t he most interesting for Unikube.

**Comment by marty-2015** [comment]
@Truthans this is still an open topic. Can we set up a meeting for this on thursday?

**Comment by marty-2015** [comment]
@Truthans this is done, please review the topics marked in red.
