### ISSUE TITLE
New graphics by Joel

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#86]
1. Unikube Workflow
2. Developers and their interaction with Kubernetes clusters

**Comment by marty-2015** [comment]
For me these new versions look fine. Pleas have a look @Schille 

Reiterated illustrations:
1. Unikube Workflow: https://drive.google.com/file/d/1DjiagCFKV1wameKczISFD5AmuliN8PH5/view?usp=sharing
2. Developers and their Interactions with a Unikube Cluster: https://drive.google.com/file/d/1xtv2-KC5L70NTxuLI_dGlaZEDbP_08sd/view?usp=sharing

**Comment by marty-2015** [comment]
Final Feedback given to Joel (03.11.)

**Comment by marty-2015** [comment]
Here are the final versions, please review @Schille 

1. Unikube Workflow: https://drive.google.com/file/d/12zLf9dD8ip_r2C5o2Z1cYqIX30zoy5WJ/view?usp=sharing
2. Developers and their Interactions with a Unikube Cluster: https://drive.google.com/file/d/1VRDNx0ZJ4ScvbCMG98VtmXFBGCoqMHcI/view?usp=sharing

**Comment by Schille** [comment]
Jepp. Now it's fine.
