### ISSUE TITLE
Create a Help Page

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#87]
Preview of Help & Support Page
https://cms-dot-blueshoe-website-v4.ew.r.appspot.com/cms/pages/91/edit/preview/

- Links on main home page
- slack login/invite
- get help/support
- get involved on github (company profile descritption)

**Comment by marty-2015** [comment]
![Bildschirmfoto 2021-11-04 um 15 43 30](https://user-images.githubusercontent.com/86047585/140334767-85cc1db6-60ac-4c5c-a500-1fdfb7334673.png)
Please review @Truthans

**Comment by Truthans** [comment]
@marty-2015 yes, this looks a lot better! Something we can then gradually do, is link up the most important guides in the first section. For example
- Getting started
- Installing the CLI
- CLI Documentation

**Comment by marty-2015** [comment]
@Truthans I have added the different guides to the list and published the help page.
URL is: https://unikube.io/help/
- Also I have added the page in the footer, under the link section - which is not visible at the moment (probably still cached)
- Should the page be linked to from somewhere else?
