### ISSUE TITLE
Video: Unikube Demo

### ISSUE THREAD

**Issue by Truthans** [unikubehq/marketing#9]
https://drive.google.com/file/d/1Y3Y4RL5pWWIQKHg1U7Nk7mTCo5SNkmT4/view?usp=sharing
- [x] Finalize script
- [x] record 2nd take
- [x] Upload on website or on YouTube

**Comment by Truthans** [comment]
New version:
https://drive.google.com/file/d/1aJySIkJQ7RG8bILoysCl9nRVN82ANDky/view?usp=sharing

**Comment by Truthans** [comment]
@marty-2015 kannst du den neuen Protoyp mal Dierk bzw. dem Kollegen zukommen lassen, sagen, dass das eine prototypische Version ist, die wir jetzt gern in "geil" hätten. Mich würde interessieren ob sie dazu Ideen haben und was das kostet.

**Comment by marty-2015** [comment]
Hab per Mail angefragt für nen Call. Du bist CC.

**Comment by Truthans** [comment]
Alright, we also need to proof reading for the script and the presentation.

**Comment by marty-2015** [comment]
Proofreading is requested.

**Comment by Schille** [comment]
How may I support this process at the moment?

**Comment by Schille** [comment]
https://drive.google.com/file/d/1tWmXoykbzAm0hpjGMZENeEdMlDfIfkmU/view?usp=sharing

**Comment by marty-2015** [comment]
> How may I support this process at the moment? Not sure if the conversation to this point is really related to the demo video?

No, the conversation belongs to the other video. Sorry.

**Comment by marty-2015** [comment]
@Schille I like the new video, it has a good quality.
@Truthans Should we put this video on our main page until we have the final "what is unikube"- video?

**Comment by Truthans** [comment]
@marty-2015 I suggest adding a additional section either above "Unikube streamlines..." or above "Features". Use the TextAndVideoSection and put the video on the left side. The text for the video should be something about the demo, i. e. what the user will learn.

**Comment by marty-2015** [comment]
@Truthans video cannot be uploaded, because of the size. I have opened a new ticket for expanding the video-plugin to YouTube integration. #52

**Comment by Truthans** [comment]
@marty-2015 well spotted. Please keep attention on this while I am gone. It's a very relevant piece of content.

**Comment by Schille** [comment]
May we close this issue?
