### ISSUE TITLE
Graphic for Naive Workflow

### ISSUE THREAD

**Issue by marty-2015** [unikubehq/marketing#90]
Update: Naive workflow, deadline 11.11.

**Comment by marty-2015** [comment]
@Schille can you please have a look at the Naive Workflow illustration?

My changes would be:
- leave out Unikube Logo on the botton
- change color of workflow 8 (or is it better to have 2/4/5/7/8 in a similar color since they are all about Kubernetes?)
- arrow from service 1 to Kubernetes Dev Cluster is missing
- write manifests small (everywhere)
- question for workflow 3: Should this be called "K8s manifests exchanegd & updated" or "K8s manifest: exchanges & updates"
- question for workflows 2/4/5: What are these actions called? Can we sum this up, so that we can write something in the caption at the top? 
- Service Conglomerate (light version) not visible
- Special Tooling arrow (dark version) white instead of blue

![Bildschirmfoto 2021-11-16 um 10 12 21](https://user-images.githubusercontent.com/86047585/141956408-ecaf7c32-ff83-4db0-a23b-ae8cdb646d8e.png)

**Comment by marty-2015** [comment]
Original Naive Workflow:
![Bildschirmfoto 2021-11-16 um 10 24 42](https://user-images.githubusercontent.com/86047585/141958338-42cf00c4-759f-45ed-96c0-97462710f7d8.png)

**Comment by Schille** [comment]
:+1:

**Comment by marty-2015** [comment]
@Schille can you please answer these two questions:
- question for workflow 3: Should this be called "K8s manifests exchanged & updated" or "K8s manifest: exchanges & updates"
- question for workflows 2/4/5: What are these actions called? Can we sum this up, so that we can write something in the caption at the top?

**Comment by marty-2015** [comment]
Exchanges & Updates of K8s manifests
Tedious infrastructure tasks

**Comment by marty-2015** [comment]
Feedback given 18.11.
